services:
  web:
    # コンテナ名
    container_name: "web"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "8080:80"
    # src配下のファイルをコンテナ内の~/va/www/html配下に配置
    volumes:
      - "./application:/var/www/html"
    # ネットワークの指定
    networks:
      - basegall-game-management-network
    depends_on:
      - baseball-game-management-app
  
  baseball-game-management-app:
    container_name: "baseball-game-management-app"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - "./application:/var/www/html"
    networks:
      - basegall-game-management-network

  baseball-game-management-db:
    # コンテナ名
    container_name: "baseball-game-management-db"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=baseball-game-management-db"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=userpassword"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./docker/db/data:/var/lib/mysql"
    networks:
      - basegall-game-management-network

# ネットワークの定義
networks:
  basegall-game-management-network:
    driver: bridge