name: Pull Request CI

on:
  pull_request:

env:
  # PHPバージョン、拡張機能はDockerfileの定義と合わせておく.
  PHP_VERSION: '8.2'
  PHP_EXTENSIONS: 'zip, pdo_mysql'

# 二重起動防止の設定
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # 静的解析
  static-analysis:
    name: PHPStan
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 分
    defaults:
      run:
        working-directory: application
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      # 💡 共通化したローカルアクションで、php、composerパッケージをセットアップ
      - name: Setup PHP and Install Dependencies
        uses: ./.github/actions/setup-php-and-composer
        with:
          php-version: ${{ env.PHP_VERSION }}
          php-extensions: ${{ env.PHP_EXTENSIONS }}
          working-directory: 'application'

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=512M

  # コード整形チェック（Pint）
  php-lint:
    name: PHP Lint (Pint)
    runs-on: ubuntu-latest
    timeout-minutes: 5 # タイムアウト設定（一般的にPintはPHPStanより早く終わるため短めに設定）
    defaults:
      run:
        working-directory: application
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP and Install Dependencies
        uses: ./.github/actions/setup-php-and-composer
        with:
          php-version: ${{ env.PHP_VERSION }}
          php-extensions: ${{ env.PHP_EXTENSIONS }}
          working-directory: 'application'

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

  # 単体テスト
  php-test:
    name: PHPUnit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [static-analysis, php-lint] # PHPStan、Lintが通った後に実行
    defaults:
      run:
        working-directory: application
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP and Install Dependencies
        uses: ./.github/actions/setup-php-and-composer
        with:
          php-version: ${{ env.PHP_VERSION }}
          php-extensions: ${{ env.PHP_EXTENSIONS }}
          working-directory: 'application'

      - name: Run PHPUnit Unit Suite
        # --testsuite オプションで「Unit」のみを指定して実行.
        # TODO FeatureテストなどをCIで導入できるよう、DBの用意なども検討する。まずはCIでのテスト導入を優先してunit testのみ実行する.
        run: ./vendor/bin/phpunit --testsuite=Unit
