name: Pull Request CI

on:
  pull_request:

jobs:
  static-analysis:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # 使用しているPHPバージョンを指定
          extension: zip, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: cd application && vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=512M